### ISSUE TITLE
[Android Bootcamp]:Project 0:Todo - Ready for Review

### ISSUE THREAD

**Issue by rehan-0601** [rehan-0601/Todo#1]
My app is complete, please review. /cc @codepathreview @codepath

Questions:
1.When i edit an item and push back my changes, i also pass the index of the item in the ArrayList. Is there a better way to do this.
2.Is there another way to set the title of an activity, Im using setTitle in the java source, can i do this from the xml?
3.Is there a way to specify the exact size of the Text Views i use within an activity?

**Comment by nesquena** [comment]
> 1.When i edit an item and push back my changes, i also pass the index of the item in the ArrayList. Is there a better way to do this.

You can either pass back the index after edit takes place OR store the index when the item is first clicked.

> 2.Is there another way to set the title of an activity, Im using setTitle in the java source, can i do this from the xml?

Yes, see [this guide](http://guides.codepath.com/android/Defining-The-ActionBar#changing-the-actionbar-icon-or-title)

> 3.Is there a way to specify the exact size of the Text Views i use within an activity?

Yes, you can do that with the property "android:width" and values like "50dp" set the exact size. Consider why this might be a bad idea though given the extensive number of types of screen sizes, densities and resolutions Android apps run on. Think "responsive web" but even more important for native apps. Hence why RelativeLayout discourages use of absolute sizes.

**Comment by nesquena** [comment]
Rehan,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 15 minute phone conversation** [here](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU). Navigate to [today's date and onward from there](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose a 15-minute slot. Let us know if none of those times work.

Once you select a slot, can you make sure to **include best number** to reach you at to the invite? Look forward to chatting soon!

**Comment by rehan-0601** [comment]
Implemented additional optional/suggested features.please review. /cc @codepathreview @codepath

**Comment by nesquena** [comment]
Nice, good to see you implemented many extensions after our chat. Will be in touch soon via email to follow up.
